name: CI

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Run tests
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rspec spec --format RspecJunitFormatter --out coverage/rspec.xml --format progress --profile 10 --color --order random
