name: Publish gem

on:
  release:
    types:
      - created

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: "${{ github.event.release.tag_name }}"

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
